### ISSUE TITLE
Incorrect format validation, number or array?

### ISSUE THREAD

**Issue by whatwoot** [pipiku915/FinMem-LLM-StockTrading#25]
### I found that the prompt specifies the format of number：

Your output should strictly conforms the following json format without any additional contents: {"summary_reason": string, "short_memory_index": number, "middle_memory_index": number, "long_memory_index": number, "reflection_memory_index": number}

### But array is needed in guardrails?
---------------------------------
I was given the following JSON response, which had problems due to incorrect values.

{
  "summary_reason": "The decision to invest in TSLA based on the observed price difference from the current to the next trading day is influenced by short-term factors.",
  "short_memory_index": -1,
  "middle_memory_index": -1,
  "long_memory_index": -1,
  "reflection_memory_index": -1
}

Help me correct the incorrect values based on the given error messages.

Error Messages:
"JSON does not match schema:\n{\n  \"$.reflection_memory_index\": [\n    \"-1 is not of type 'array'\"\n  ],\n  \"$.long_memory_index\": [\n    \"-1 is not of type 'array'\"\n  ],\n  \"$.middle_memory_index\": [\n    \"-1 is not of type 'array'\"\n  ],\n  \"$.short_memory_index\": [\n    \"-1 is not of type 'array'\"\n  ]\n}"

**Comment by morning-star-001** [comment]
The generated data for the Fake-Sample-Data is not clear, Do you mind elaborating on how you were able to generate data for use?

A guide for instance on generating tsla.pkl

**Comment by Carolyn-Jiang** [comment]
The output files generated by the script “05-get_sentiment_by_ticker.py” are named with the prefix “subset_symbols_” followed by the corresponding ticker name. These files serve as the final input for FinMem. To use them, you can simply rename the file to “<ticker name>.pkl”.


You can use this model via Gitpod, please refer to this video. https://github.com/pipiku915/FinMem-LLM-StockTrading/blob/main/FinMem.mp4

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by morning-star-001** [comment]
thanks for the response..

Got this error

FileNotFoundError: [Errno 2] No such file or directory: './data/05_env_data/env_data.pkl'

Although I created the folder and used the env_data.pkl found in the Fake-Sample-Data, and got another error response:

`Ticker list: ------ ['BAC', 'DIS', 'GM', 'MRNA', 'NVDA', 'PFE']
  0%|                                                                                                                                              | 0/496 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/llm/llm/./data-pipeline/05-get_sentiment_by_ticker.py", line 150, in <module>
    export_sub_symbol(cur_symbol_lst, senti_model_type = 'FinBERT')  
  File "/llm/llm/./data-pipeline/05-get_sentiment_by_ticker.py", line 132, in export_sub_symbol
    new_dict, ticker_dict_byDate = subset_symbol_dict(input_dir, cur_symbol_0)
  File "/llm/llm/./data-pipeline/05-get_sentiment_by_ticker.py", line 28, in subset_symbol_dict
    cur_filing_q = v[2]['filling_q']  # form q
KeyError: 'filling_q'
`

**Comment by morning-star-001** [comment]
The above error has been debugged, been a typo in the env_data.pkl itself In the filling_q key.

A new error did surface though.

`Traceback (most recent call last):
  File "/llm/llm/./data-pipeline/05-get_sentiment_by_ticker.py", line 151, in <module>
    export_sub_symbol(cur_symbol_lst, senti_model_type = 'FinBERT')  
  File "/llm/llm/./data-pipeline/05-get_sentiment_by_ticker.py", line 137, in export_sub_symbol
    print('finBERT Date" 2023-05-30: ----- ', new_dict[datetime.date(2023, 5, 30)]['news'])
KeyError: datetime.date(2023, 5, 30)
`

**Comment by Carolyn-Jiang** [comment]
This is because fake data does not contain data for this day. You can comment out all prints.
________________________________

**Comment by morning-star-001** [comment]
Tried other dates in the fake data like "2017, 12, 29" for instance, still prints the same error, could you give one date that might work?

**Comment by morning-star-001** [comment]
I have been to pass the pkl generation, however on using "run.py" this error get thrown "start_date and end_date must be in env_data_pkl keys"

**Comment by morning-star-001** [comment]
Also finding it very tedious to use the API Data-pipelines because files are missing like price_data.parquet for example.

Was this project ever intended to be tried out by others. It's filesystem structure says otherwise...

**Comment by morning-star-001** [comment]
@Carolyn-Jiang Could you helo with the price_data.parquet file please

**Comment by Carolyn-Jiang** [comment]
Please refer to https://coling2025cryptotrading.thefin.ai

And https://github.com/felis33/coling-cryptocurrency-trading-challenge

You can find open-source data and start kit here.
________________________________

**Comment by whatwoot** [comment]
@Carolyn-Jiang 

Any idea for my question？Thank u a lot！

> ### I found that the prompt specifies the format of number：
> Your output should strictly conforms the following json format without any additional contents: {"summary_reason": string, "short_memory_index": number, "middle_memory_index": number, "long_memory_index": number, "reflection_memory_index": number}
> 
> ### But array is needed in guardrails?
> I was given the following JSON response, which had problems due to incorrect values.
> 
> { "summary_reason": "The decision to invest in TSLA based on the observed price difference from the current to the next trading day is influenced by short-term factors.", "short_memory_index": -1, "middle_memory_index": -1, "long_memory_index": -1, "reflection_memory_index": -1 }
> 
> Help me correct the incorrect values based on the given error messages.
> 
> Error Messages: "JSON does not match schema:\n{\n "$.reflection_memory_index": [\n "-1 is not of type 'array'"\n ],\n "$.long_memory_index": [\n "-1 is not of type 'array'"\n ],\n "$.middle_memory_index": [\n "-1 is not of type 'array'"\n ],\n "$.short_memory_index": [\n "-1 is not of type 'array'"\n ]\n}"
